version: '3.11'

services:
  rabbit-mq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitMQ'
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
    ports:
      - 5672:$RABBITMQ_QUEUE_PORT
      - 15672:$RABBITMQ_MANAGEMENT_PORT
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge